server:
  port : ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    com:
      avaloq:
        dice:
          simulation: ${LOG_LEVEL:INFO}

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

  data:
    mongodb:
      uri: ${DB_URL:mongodb://root:rootpassword@localhost:27017/dice-simulations}

---
spring:
  profiles: test